CREATE DATABASE IF NOT EXISTS emargement;
USE emargement;

CREATE TABLE presences (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    licence VARCHAR(6) NOT NULL,
    date_presence TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
